// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class adviceofcvcqrs
    {
        public int? advice_cvc_id { get; set; }
        public int? advice_cvc_first_casespreviousqtr { get; set; }
        public int? advice_cvc_first_casesduringqtr { get; set; }
        public int? advice_cvc_first_adviceduringqtr { get; set; }
        public int? advice_cvc_first_adviceawaitedcvc { get; set; }
        public int? advice_cvc_second_casespreviousqtr { get; set; }
        public int? advice_cvc_second_casesduringqtr { get; set; }
        public int? advice_cvc_second_adviceduringqtr { get; set; }
        public int? advice_cvc_second_adviceawaitedcvc { get; set; }
        public int? advice_cvc_firstreconsider_casespreviousqtr { get; set; }
        public byte? advice_cvc_firstreconsider_casesduringqtr { get; set; }
        public byte? advice_cvc_firstreconsider_adviceduringqtr { get; set; }
        public int? advice_cvc_firstreconsider_adviceawaitedcvc { get; set; }
        public int? advice_cvc_secondreconsider_casespreviousqtr { get; set; }
        public int? advice_cvc_secondreconsider_casesduringqtr { get; set; }
        public int? advice_cvc_secondreconsider_adviceduringqtr { get; set; }
        public int? advice_cvc_secondreconsider_adviceawaitedcvc { get; set; }
        public int? advice_cvc_total_casespreviousqtr { get; set; }
        public int? advice_cvc_total_casesduringqtr { get; set; }
        public int? advice_cvc_total_adviceduringqtr { get; set; }
        public int? advice_cvc_total_adviceawaitedcvc { get; set; }
        public int? action_cvc_firstmajor_openingbalance { get; set; }
        public int? action_cvc_firstmajor_adviceduringqtr { get; set; }
        public int? action_cvc_firstmajor_disposed { get; set; }
        public int? action_cvc_firstmajor_balancepending { get; set; }
        public int? action_cvc_firstmajor_greaterone { get; set; }
        public int? action_cvc_firstmajor_onetothree { get; set; }
        public int? action_cvc_firstmajor_threetosix { get; set; }
        public int? action_cvc_firstmajor_lesssix { get; set; }
        public int? action_cvc_firstminor_openingbalance { get; set; }
        public int? action_cvc_firstminor_adviceduringqtr { get; set; }
        public int? action_cvc_firstminor_disposed { get; set; }
        public int? action_cvc_firstminor_balancepending { get; set; }
        public int? action_cvc_firstminor_greaterone { get; set; }
        public int? action_cvc_firstminor_onetothree { get; set; }
        public int? action_cvc_firstminor_threetosix { get; set; }
        public int? action_cvc_firstminor_lesssix { get; set; }
        public int? action_cvc_secondmajor_openingbalance { get; set; }
        public int? action_cvc_secondmajor_adviceduringqtr { get; set; }
        public int? action_cvc_secondmajor_disposed { get; set; }
        public int? action_cvc_secondmajor_balancepending { get; set; }
        public int? action_cvc_secondmajor_greaterone { get; set; }
        public int? action_cvc_secondmajor_onetothree { get; set; }
        public int? action_cvc_secondmajor_threetosix { get; set; }
        public int? action_cvc_secondmajor_lesssix { get; set; }
        public int? action_cvc_secondminor_openingbalance { get; set; }
        public int? action_cvc_secondminor_adviceduringqtr { get; set; }
        public int? action_cvc_secondminor_disposed { get; set; }
        public int? action_cvc_secondminor_balancepending { get; set; }
        public int? action_cvc_secondminor_greaterone { get; set; }
        public int? action_cvc_secondminor_onetothree { get; set; }
        public int? action_cvc_secondminor_threetosix { get; set; }
        public int? action_cvc_secondminor_lesssix { get; set; }
        public int? action_cvc_total_openingbalance { get; set; }
        public int? action_cvc_total_adviceduringqtr { get; set; }
        public int? action_cvc_total_disposed { get; set; }
        public int? action_cvc_total_balancepending { get; set; }
        public int? action_cvc_total_greaterone { get; set; }
        public int? action_cvc_total_onetothree { get; set; }
        public int? action_cvc_total_threetosix { get; set; }
        public int? action_cvc_total_lesssix { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_typecvcadvice { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_cvcfilenumber { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_dept_ref_number { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_name_designation { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_actiontaken_da { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_typecvcadvice { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_cvcfilenumber { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_dept_ref_number { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_name_designation { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_actiontaken_da { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_typecvcadvice { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_cvcfilenumber { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_dept_ref_number { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_name_designation { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_actiontaken_da { get; set; }
        [StringLength(50)]
        public string appellate_deviation_firststage_actiontaken_aa { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_typecvcadvice { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_cvcfilenumber { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_dept_ref_number { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_name_designation { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_actiontaken_da { get; set; }
        [StringLength(50)]
        public string appellate_deviation_secondstage_actiontaken_aa { get; set; }
        [StringLength(50)]
        public string create_date { get; set; }
        [StringLength(50)]
        public string user_id { get; set; }
        [StringLength(50)]
        public string update_date { get; set; }
        [StringLength(50)]
        public string last_user_id { get; set; }
        public int? qpr_id { get; set; }
        [StringLength(50)]
        public string ip { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_firststage_name_designation_da { get; set; }
        [StringLength(50)]
        public string deviation_cvc_advice_secondstage_name_designation_da { get; set; }
    }
}