// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class againstchargedtable
    {
        [StringLength(200)]
        public string departproceedings_detailsinquiry_chargedofficer { get; set; }
        [StringLength(50)]
        public string departproceedings_detailsinquiry_chargesheet { get; set; }
        [StringLength(50)]
        public string departproceedings_detailsinquiry_ioappointment { get; set; }
        [Column(TypeName = "date")]
        public DateTime? departproceedings_detailsinquiry_superannuation { get; set; }
        public string departproceedings_detailsinquiry_remarks { get; set; }
        [StringLength(50)]
        public string used_ip { get; set; }
        public short? pend_id { get; set; }
        public short? qpr_id { get; set; }
    }
}