// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class agewisependency
    {
        public int? pend_id { get; set; }
        public long? qpr_id { get; set; }
        public string prosependingnamedesig { get; set; }
        public string prosependingdaterecommend { get; set; }
        public string prosependingdatereceipt { get; set; }
        public string prosependingstatusrequest { get; set; }
        public string prosependingnameauthority { get; set; }
        public string used_ip { get; set; }
        public string prosependingcbifirno { get; set; }
        public string prosependingsanctionpc { get; set; }
    }
}