// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cdi_nom
    {
        public int? section { get; set; }
        [StringLength(2000)]
        public string file_no { get; set; }
        public int? sno { get; set; }
        [StringLength(2000)]
        public string io_type { get; set; }
        [StringLength(2000)]
        public string nom_date { get; set; }
        [StringLength(2000)]
        public string cdi_name { get; set; }
        public bool? cdi_apptd { get; set; }
        [StringLength(2000)]
        public string dt_apptd { get; set; }
        public bool? io_rep_recd { get; set; }
        [StringLength(2000)]
        public string io_rep_recd_date { get; set; }
        [StringLength(2000)]
        public string io_recom { get; set; }
        [StringLength(2000)]
        public string rec_dt { get; set; }
        [StringLength(2000)]
        public string cdi_ref_no { get; set; }
        [StringLength(2000)]
        public string cdi_rep_sent_dt { get; set; }
        public bool? disp_auth_comm_recd { get; set; }
        [StringLength(2000)]
        public string disp_auth_comm_dt { get; set; }
        [StringLength(2000)]
        public string last_updated { get; set; }
    }
}