// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class complain
    {
        public long? complaintnumber { get; set; }
        [StringLength(500)]
        public string sendername { get; set; }
        [Column(TypeName = "date")]
        public DateTime? complaindate { get; set; }
        [StringLength(1000)]
        public string address { get; set; }
        [StringLength(1000)]
        public string address2 { get; set; }
        [StringLength(100)]
        public string state { get; set; }
        [StringLength(500)]
        public string city { get; set; }
        public int? pinno { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [StringLength(250)]
        public string complaintagainstname { get; set; }
        [StringLength(1000)]
        public string designation { get; set; }
        [StringLength(250)]
        public string organization { get; set; }
        public bool? whetherfasttrack { get; set; }
        [StringLength(100)]
        public string complainttype { get; set; }
        [StringLength(1000)]
        public string actiontaken { get; set; }
        [StringLength(500)]
        public string uploadscandocument { get; set; }
        [Column(TypeName = "date")]
        public DateTime? createddate { get; set; }
        public int? usercode { get; set; }
        [StringLength(250)]
        public string documentstatus { get; set; }
        [StringLength(250)]
        public string gistallegation { get; set; }
        [StringLength(250)]
        public string bodecision { get; set; }
        [StringLength(250)]
        public string boircondate { get; set; }
        [StringLength(250)]
        public string boirremidate { get; set; }
        [StringLength(250)]
        public string boirconrecdate { get; set; }
        [StringLength(250)]
        public string boirfinaldec { get; set; }
        [StringLength(250)]
        public string boirfileno { get; set; }
        [StringLength(250)]
        public string boirackdate { get; set; }
        [StringLength(250)]
        public string confirm_cvo { get; set; }
        [StringLength(250)]
        public string bonaackdate { get; set; }
        [StringLength(250)]
        public string boothacksentdate { get; set; }
        [StringLength(250)]
        public string boothconcvo { get; set; }
        [StringLength(250)]
        public string boothconsendate { get; set; }
        [StringLength(250)]
        public string boothremsendate { get; set; }
        [StringLength(250)]
        public string boothconrecdat { get; set; }
        [StringLength(250)]
        public string whetherfastrack { get; set; }
        [StringLength(250)]
        public string filenumber { get; set; }
        [StringLength(250)]
        public string boothacksntdate { get; set; }
        [StringLength(250)]
        public string complaint { get; set; }
        [StringLength(250)]
        public string dairyid { get; set; }
        [StringLength(250)]
        public string recipientname { get; set; }
        [StringLength(250)]
        public string willingdepose { get; set; }
        [StringLength(250)]
        public string dairystatus { get; set; }
        [StringLength(250)]
        public string rolltype { get; set; }
        public DateTime? forwarddate { get; set; }
        public string detailofallegation { get; set; }
        public byte? section { get; set; }
        [StringLength(250)]
        public string bofiledackdate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? bofinaldecdate { get; set; }
        [StringLength(250)]
        public string boname { get; set; }
        [StringLength(250)]
        public string bonaomdate { get; set; }
        [StringLength(250)]
        public string bofileddate { get; set; }
        public long? mobileno { get; set; }
        [StringLength(250)]
        public string organisationcode { get; set; }
        public bool? status { get; set; }
        public bool? cvoview { get; set; }
        [StringLength(250)]
        public string confirmcvo { get; set; }
        [StringLength(250)]
        public string complaintsentfrom { get; set; }
        [StringLength(250)]
        public string closedby { get; set; }
        public bool? complainstatus { get; set; }
        [StringLength(250)]
        public string ackgenby { get; set; }
        [StringLength(250)]
        public string reasontochangefile { get; set; }
        [StringLength(250)]
        public string filechangeby { get; set; }
        [Column(TypeName = "date")]
        public DateTime? bodecisiondate { get; set; }
        [StringLength(50)]
        public string ipcapture { get; set; }
        [StringLength(100)]
        public string byuserid { get; set; }
        [StringLength(50)]
        public string ondate { get; set; }
        [StringLength(50)]
        public string important { get; set; }
    }
}