// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cpa_complaint
    {
        public string complaintnumber { get; set; }
        public string complaint { get; set; }
        public string section { get; set; }
        public string doc_id { get; set; }
        public string subject_name { get; set; }
        public string sendername { get; set; }
        public string address { get; set; }
        public string mobileno { get; set; }
        public string email { get; set; }
        public string complaint_against_name { get; set; }
        public string complaintagainstname { get; set; }
        public string complaint_description { get; set; }
        public string complaindate { get; set; }
        public string createddate { get; set; }
        public string created_user_id { get; set; }
        public string creator_emp_name { get; set; }
        public string mode_of_receipt_type { get; set; }
        public string complaint_type_name { get; set; }
        public string mode_of_receipt_name { get; set; }
        public string id { get; set; }
        public string corr_created_date { get; set; }
        public string ministry_name { get; set; }
        public string organization { get; set; }
        public string bodecisiondate { get; set; }
        public string corr_id { get; set; }
        public string file_no { get; set; }
        public string corr_desc { get; set; }
        public string file_desc { get; set; }
        public string cvc_file_no { get; set; }
        public string complaint_summary { get; set; }
        public string corrdate { get; set; }
        public string file_creation_date { get; set; }
        public string org_id { get; set; }
        public string reason_for_action { get; set; }
        public string cmpln_sent_dt { get; set; }
        public string investigation_report { get; set; }
        public string factual_report { get; set; }
        public string filed { get; set; }
        public string direct_invest { get; set; }
        public string necessary_action { get; set; }
        public string action_taken_report { get; set; }
        public string discrete_veri { get; set; }
        public string org_file_name { get; set; }
        public string enc_file_name { get; set; }
        public string file_location { get; set; }
    }
}