// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cvcadvicetable
    {
        public long? pend_id { get; set; }
        public long? qpr_id { get; set; }
        public string stagetype { get; set; }
        public string deviation_cvc_advice_firststage_typecvcadvice { get; set; }
        public string deviation_cvc_advice_firststage_cvcfilenumber { get; set; }
        public string deviation_cvc_advice_firststage_dept_ref_number { get; set; }
        public string deviation_cvc_advice_firststage_name_designation { get; set; }
        public string deviation_cvc_advice_firststage_actiontaken_da { get; set; }
        public string deviation_cvc_advice_firststage_actiontaken_aa { get; set; }
        public string used_ip { get; set; }
    }
}