// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cvo
    {
        public int? complainid { get; set; }
        public string complaintnumber { get; set; }
        public string sourcecomplaint { get; set; }
        public string gistallegations { get; set; }
        [Column(TypeName = "date")]
        public DateTime? duedatereport { get; set; }
        public string cvofile { get; set; }
        public string cvofilenumber { get; set; }
        public string observation { get; set; }
        public string responseofficialconcerned { get; set; }
        public string counterresponse { get; set; }
        public string conclusion { get; set; }
        public string responsibilityofofficials { get; set; }
        public string recommendationaction { get; set; }
        public string systematicimprovement { get; set; }
        public string assurancememo { get; set; }
        public string biodataofficials { get; set; }
        public string officername { get; set; }
        public string officerdesignation { get; set; }
        public string investigationopendate { get; set; }
        public string investigationclosedate { get; set; }
        public string decision { get; set; }
        public string decisiondate { get; set; }
        public string remark { get; set; }
        public string cvcjuri { get; set; }
        public string referfirststage { get; set; }
        public string recommendationactiondate { get; set; }
        public string referfirststagedate { get; set; }
        public string assurancememodate { get; set; }
        public string cvcconf { get; set; }
        public string confirmationdate { get; set; }
        public string cvcrecv { get; set; }
        public string receiveddate { get; set; }
        public string cvcrem { get; set; }
        public string reminderdate { get; set; }
    }
}