// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cvo_detail
    {
        [Required]
        public string sourceofcomplaint { get; set; }
        [StringLength(255)]
        public string gistofallegations { get; set; }
        [StringLength(255)]
        public string duedateofreport { get; set; }
        [StringLength(255)]
        public string cvofilenumber { get; set; }
        [StringLength(255)]
        public string observation { get; set; }
        [StringLength(255)]
        public string responseofficialconcerned { get; set; }
        [StringLength(255)]
        public string counterresponse { get; set; }
        [StringLength(255)]
        public string conclusion { get; set; }
        [StringLength(255)]
        public string responsibilityofficials { get; set; }
        [StringLength(255)]
        public string recommendationaction { get; set; }
        [StringLength(255)]
        public string recommendationimprovement { get; set; }
        [StringLength(255)]
        public string assurancememo { get; set; }
        [StringLength(255)]
        public string biodataofofficials { get; set; }
    }
}