// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class cvomonthlyreport
    {
        public int? year { get; set; }
        public string uploadedfile { get; set; }
        public string organisationcode { get; set; }
        public string organisation { get; set; }
        public string branchofficer { get; set; }
        public string branchofficercode { get; set; }
        public string cvoname { get; set; }
        public string cvoid { get; set; }
        [Column(TypeName = "date")]
        public DateTime? reportsubmitdate { get; set; }
        public int? month { get; set; }
    }
}