// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class departmentalproceedingsqrs
    {
        public int? departproceedings_id { get; set; }
        public int? departproceedingsmajor_cvc_lastqtr { get; set; }
        public int? departproceedingsmajor_cvc_inquiries { get; set; }
        public int? departproceedingsmajor_cvc_total { get; set; }
        public int? departproceedingsmajor_cvc_reportsio { get; set; }
        public int? departproceedingsmajor_cvc_enquiries { get; set; }
        public int? departproceedingsmajor_cvc_greatersix { get; set; }
        public int? departproceedingsmajor_cvc_sixtotwelve { get; set; }
        public int? departproceedingsmajor_cvc_twelvetoeighteen { get; set; }
        public int? departproceedingsmajor_cvc_lesseighteen { get; set; }
        public int? departproceedingsmajor_other_lastqtr { get; set; }
        public int? departproceedingsmajor_other_inquiries { get; set; }
        public int? departproceedingsmajor_other_total { get; set; }
        public int? departproceedingsmajor_other_reportsio { get; set; }
        public int? departproceedingsmajor_other_enquiries { get; set; }
        public int? departproceedingsmajor_other_greatersix { get; set; }
        public int? departproceedingsmajor_other_sixtotwelve { get; set; }
        public int? departproceedingsmajor_other_twelvetoeighteen { get; set; }
        public int? departproceedingsmajor_other_lesseighteen { get; set; }
        public int? departproceedingsmajor_total_lastqtr { get; set; }
        public int? departproceedingsmajor_total_inquiries { get; set; }
        public int? departproceedingsmajor_total_total { get; set; }
        public int? departproceedingsmajor_total_reportsio { get; set; }
        public int? departproceedingsmajor_total_enquiries { get; set; }
        public int? departproceedingsmajor_total_greatersix { get; set; }
        public int? departproceedingsmajor_total_sixtotwelve { get; set; }
        public int? departproceedingsmajor_total_twelvetoeighteen { get; set; }
        public int? departproceedingsmajor_total_lesseighteen { get; set; }
        public int? departproceedings_minor_cvc_lastqtr { get; set; }
        public int? departproceedings_minor_cvc_inquiries { get; set; }
        public int? departproceedings_minor_cvc_total { get; set; }
        public int? departproceedings_minor_cvc_reportsio { get; set; }
        public int? departproceedings_minor_cvc_enquiries { get; set; }
        public int? departproceedings_minor_cvc_greatersix { get; set; }
        public int? departproceedings_minor_cvc_sixtotwelve { get; set; }
        public int? departproceedings_minor_cvc_twelvetoeighteen { get; set; }
        public int? departproceedings_minor_cvc_lesseighteen { get; set; }
        public int? departproceedings_minor_other_lastqtr { get; set; }
        public int? departproceedings_minor_other_inquiries { get; set; }
        public int? departproceedings_minor_other_total { get; set; }
        public int? departproceedings_minor_other_reportsio { get; set; }
        public int? departproceedings_minor_other_enquiries { get; set; }
        public int? departproceedings_minor_other_greatersix { get; set; }
        public int? departproceedings_minor_other_sixtotwelve { get; set; }
        public int? departproceedings_minor_other_twelvetoeighteen { get; set; }
        public int? departproceedings_minor_other_lesseighteen { get; set; }
        public int? departproceedings_minor_total_lastqtr { get; set; }
        public int? departproceedings_minor_total_inquiries { get; set; }
        public int? departproceedings_minor_total { get; set; }
        public int? departproceedings_minor_total_reportsio { get; set; }
        public int? departproceedings_minor_total_enquiries { get; set; }
        public int? departproceedings_minor_total_greatersix { get; set; }
        public int? departproceedings_minor_total_sixtotwelve { get; set; }
        public int? departproceedings_minor_total_twelvetoeighteen { get; set; }
        public int? departproceedings_minor_total_lesseighteen { get; set; }
        public int? departproceedings_detailsinquiry_serialnumber { get; set; }
        [StringLength(2000)]
        public string departproceedings_detailsinquiry_chargedofficer { get; set; }
        [StringLength(2000)]
        public string departproceedings_detailsinquiry_chargesheet { get; set; }
        [StringLength(2000)]
        public string departproceedings_detailsinquiry_ioappointment { get; set; }
        [StringLength(2000)]
        public string departproceedings_detailsinquiry_superannuation { get; set; }
        [StringLength(2000)]
        public string departproceedings_detailsinquiry_remarks { get; set; }
        [StringLength(2000)]
        public string create_date { get; set; }
        [StringLength(2000)]
        public string user_id { get; set; }
        [StringLength(2000)]
        public string update_date { get; set; }
        [StringLength(2000)]
        public string last_user_id { get; set; }
        public int? qpr_id { get; set; }
        [StringLength(2000)]
        public string ip { get; set; }
    }
}