// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class fnsstage
    {
        public int? section { get; set; }
        public string file_no { get; set; }
        public int? sno { get; set; }
        public string cbi_rec { get; set; }
        public string cbi_date { get; set; }
        public string agen_rec { get; set; }
        public string rec_dt { get; set; }
        public string fsadvcode { get; set; }
        public string fscompdt { get; set; }
        public string fssendt { get; set; }
        public int? compreqd { get; set; }
        public int? comprecd { get; set; }
        public string compdate { get; set; }
        public string fsrecon_dept_code { get; set; }
        public string fsrecon_dept_date { get; set; }
        public string fsrecon_comm_code { get; set; }
        public string fsrecon_comm_comp_dt { get; set; }
        public string fsrecon_comm_send_dt { get; set; }
        public int? chrg_sht_iss { get; set; }
        public string iss_dt { get; set; }
        public int? io_reqd { get; set; }
        public string status { get; set; }
        public string last_updated { get; set; }
        public int? sys_imp { get; set; }
        public string sys_detail { get; set; }
        public int? sys_comp_rec { get; set; }
        public string sys_comp_date { get; set; }
        public string ssadvcode { get; set; }
        public string sscompdt { get; set; }
        public string sssendt { get; set; }
    }
}