// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class forward1
    {
        public long? fsno { get; set; }
        public string forwardedcount { get; set; }
        public string fromusercode { get; set; }
        public string tousercode { get; set; }
        public string status { get; set; }
        public string fdate { get; set; }
        public string complaintnumber { get; set; }
    }
}