// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class groupmap
    {
        public string mincod { get; set; }
        public string name { get; set; }
        public string orgcod { get; set; }
        public string orgname1 { get; set; }
        public string orgname2 { get; set; }
    }
}