// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class ind_det
    {
        public string section { get; set; }
        public string file_no { get; set; }
        public string sno { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string desig { get; set; }
        public string grade { get; set; }
        public string service { get; set; }
        public string org { get; set; }
        public string dept_ref_no { get; set; }
        public string birth_dt { get; set; }
        public string ret_dt { get; set; }
        public string ind_id { get; set; }
        public string last_updated { get; set; }
    }
}