// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class login_details
    {
        [Required]
        public string usercode { get; set; }
        [Required]
        public string userid { get; set; }
        [Required]
        public string password { get; set; }
        [Required]
        public string firstname { get; set; }
        [Required]
        public string enddate { get; set; }
        [Required]
        public string mobileno { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string organisation { get; set; }
        [Required]
        public string designation { get; set; }
        [Required]
        public string loginroll { get; set; }
        [Required]
        public string logintype { get; set; }
    }
}