// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class Login
    {
        [Required(ErrorMessage = "Username is required.")]
        public string Username { get; set; }

        [Required(ErrorMessage = "Password is required.")]
        public string Password { get; set; }

        [StringLength(50)]
        public string Role { get; set; }

        [Required(ErrorMessage = "Captcha is required.")]
        [Display(Name ="Captcha")]
        public string CaptchaAnswer { get; set; }

        public string ImageData { get; set; }
    }
}