// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class login_history
    {
        [Required]
        public string id { get; set; }
        [Required]
        public string ipaddress { get; set; }
        [Required]
        public string status { get; set; }
        public string username { get; set; }
        [Required]
        public string time { get; set; }
        public string login { get; set; }
        public string logout { get; set; }
        public string login_failure { get; set; }
        public string activity { get; set; }
    }
}