// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class logs
    {
        public int? id { get; set; }
        public string ipaddress { get; set; }
        public string status { get; set; }
        public string username { get; set; }
        public string time { get; set; }
        public string activity { get; set; }
    }
}