// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class morecomplainee
    {
        public int? morecomplainid { get; set; }
        public string complaineename { get; set; }
        public string desiganation { get; set; }
        public string complaintnumber { get; set; }
    }
}