// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class noting
    {
        public string notingid { get; set; }
        public string complaintnumber { get; set; }
        public string notername { get; set; }
        public string desiganation { get; set; }
        public string notingmessage1 { get; set; }
        public string notingmessage2 { get; set; }
        public string notingmessage3 { get; set; }
        public string forwardto { get; set; }
        public string notingdate { get; set; }
        public string ipcapture { get; set; }
        public string byuserid { get; set; }
        public string ondate { get; set; }
        public string name { get; set; }
    }
}