// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class orgadd
    {
        public int? section { get; set; }
        public string orgcod { get; set; }
        public string depcod { get; set; }
        public string mincod { get; set; }
        public string orgnam1 { get; set; }
        public string orgnam2 { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string addr3 { get; set; }
        public string addr4 { get; set; }
        public string addr5 { get; set; }
        public string ph_no_1 { get; set; }
        public string ph_no_2 { get; set; }
        public string fax { get; set; }
        public string telex { get; set; }
        public string grams { get; set; }
        public string ph_del_res { get; set; }
        public string psucod { get; set; }
        public string selectd { get; set; }
        public string schlvl { get; set; }
        public string jobcod { get; set; }
        [Column("checked")]
        public string _checked { get; set; }
        public string region { get; set; }
        public string email { get; set; }
    }
}