// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class pend
    {
        public int? pend_id { get; set; }
        public int? section { get; set; }
        public int? yer { get; set; }
        public int? mnt { get; set; }
        public int? sl_no { get; set; }
        public string file_no { get; set; }
        public string sno { get; set; }
        public string name { get; set; }
        public string pend_type { get; set; }
        public string pend_date { get; set; }
        public string ref_type { get; set; }
        public string sent_to_cte { get; set; }
        public string dt_sent_cte { get; set; }
        public string recv_from_cte { get; set; }
        public string dt_from_cte { get; set; }
        public string dt_sent_cvo { get; set; }
        public string cvo_recom { get; set; }
        public string cvo_recom_dt { get; set; }
        public string comm_adv { get; set; }
        public string comp_dt { get; set; }
        public string stage { get; set; }
        public string bocode { get; set; }
        public string subm { get; set; }
    }
}