// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class pincode
    {
        public string officename { get; set; }
        [Column("pincode")]
        public long? pincode1 { get; set; }
        public string officetype { get; set; }
        public string deliverystatus { get; set; }
        public string divisionname { get; set; }
        public string regionname { get; set; }
        public string circlename { get; set; }
        public string taluk { get; set; }
        public string districtname { get; set; }
        public string statename { get; set; }
    }
}