// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class preventivevigi_a_qpr
    {
        [StringLength(50)]
        public string preventivevigi_a_id { get; set; }
        [StringLength(50)]
        public string preventive_vigilance_id { get; set; }
        [StringLength(50)]
        public string preventivevigi_a_detailsvigi_subsidiaries_serial_number { get; set; }
        [StringLength(1000)]
        public string preventivevigi_a_detailsvigi_subsidiaries_nameofsub { get; set; }
        [StringLength(1000)]
        public string preventivevigi_a_detailsvigi_subsidiaries_staff_appointed { get; set; }
        [StringLength(1000)]
        public string preventivevigi_a_detailsvigi_subsidiaries_methodofcontrol { get; set; }
        public int? qpr_id { get; set; }
        [StringLength(50)]
        public string ip { get; set; }
    }
}