// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class proprofile
    {
        public int? profile_id { get; set; }
        public string name { get; set; }
        public string service { get; set; }
        public string orgname { get; set; }
        public string orgcode { get; set; }
        public string dob { get; set; }
        public string suannuation { get; set; }
        public string eduqualification { get; set; }
        public string training { get; set; }
        public string document { get; set; }
        public string createddate { get; set; }
        public string updatedate { get; set; }
    }
}