// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class prosecutionsanctionsqrs
    {
        public string prosecutionsanctions_id { get; set; }
        public string prosesanctgroupcopeningbalance { get; set; }
        public string prosesanctgroupcreciveqtr { get; set; }
        public string prosesanctgroupctotal { get; set; }
        public string prosesanctgroupcsanctiongranted { get; set; }
        public string prosesanctgroupcsanctionrefused { get; set; }
        public string prosesanctgroupcbalancepending { get; set; }
        public string prosesanctgroupcgreaterthree { get; set; }
        public string prosesanctgroupcthreetosix { get; set; }
        public string prosesanctgroupclesssix { get; set; }
        public string prosesanctgroupbopeningbalance { get; set; }
        public string prosesanctgroupbreciveqtr { get; set; }
        public string prosesanctgroupbtotal { get; set; }
        public string prosesanctgroupbsanctiongranted { get; set; }
        public string prosesanctgroupbsanctionrefused { get; set; }
        public string prosesanctgroupbbalancepending { get; set; }
        public string prosesanctgroupbgreaterthree { get; set; }
        public string prosesanctgroupbthreetosix { get; set; }
        public string prosesanctgroupblesssix { get; set; }
        public string prosesanctgroupaopeningbalance { get; set; }
        public string prosesanctgroupareciveqtr { get; set; }
        public string prosesanctgroupatotal { get; set; }
        public string prosesanctgroupasanctiongranted { get; set; }
        public string prosesanctgroupasanctionrefused { get; set; }
        public string prosesanctgroupabalancepending { get; set; }
        public string prosesanctgroupagreaterthree { get; set; }
        public string prosesanctgroupathreetosix { get; set; }
        public string prosesanctgroupalesssix { get; set; }
        public string prosesanctjsopeningbalance { get; set; }
        public string prosesanctjsreciveqtr { get; set; }
        public string prosesanctjstotal { get; set; }
        public string prosesanctjssanctiongranted { get; set; }
        public string prosesanctjssanctionrefused { get; set; }
        public string prosesanctjsbalancepending { get; set; }
        public string prosesanctjsgreaterthree { get; set; }
        public string prosesanctjsthreetosix { get; set; }
        public string prosesanctjslesssix { get; set; }
        public string prosesancttotalopeningbalance { get; set; }
        public string prosesancttotalreciveqtr { get; set; }
        public string prosesancttotal { get; set; }
        public string prosesancttotalsanctiongranted { get; set; }
        public string prosesancttotalsanctionrefused { get; set; }
        public string prosesancttotalbalancepending { get; set; }
        public string prosesancttotalgreaterthree { get; set; }
        public string prosesancttotalthreetosix { get; set; }
        public string prosesancttotallesssix { get; set; }
        public string prosependingserialnumber { get; set; }
        public string prosevigiofficersuspension { get; set; }
        public string prosevigisuspensionordered { get; set; }
        public string prosevigitotal { get; set; }
        public string prosevigisuspensionqtr { get; set; }
        public string prosevigisuspensionendqtr { get; set; }
        public string create_date { get; set; }
        public string user_id { get; set; }
        public string update_date { get; set; }
        public string last_user_id { get; set; }
        public string qpr_id { get; set; }
        public string ip { get; set; }
        public string prosependingnameauthority { get; set; }
        public string prosependingnamedesig { get; set; }
        public string prosependingstatusrequest { get; set; }
        public string prosependingdaterecommend { get; set; }
        public string prosependingdatereceipt { get; set; }
        public string prosependingcbifirno { get; set; }
        public string prosependingsanctionpc { get; set; }
    }
}