// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class public_procurement
    {
        [Key]
        public int refno { get; set; }
        [Column(TypeName = "date")]
        public DateTime? createddate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? submitdate { get; set; }
        public bool? submitflag { get; set; }
        public string ip { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string orgname { get; set; }
        public string address { get; set; }
        public string contractorsuggestion { get; set; }
        public string othersuggestion { get; set; }
    }
}