// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class qpr
    {
        [StringLength(500)]
        public string userid { get; set; }
        [StringLength(500)]
        public string orgname { get; set; }
        [StringLength(50)]
        public string orgcode { get; set; }
        [StringLength(50)]
        public string qtrreport { get; set; }
        [StringLength(50)]
        public string qtryear { get; set; }
        [StringLength(500)]
        public string contactnumberoffice { get; set; }
        [StringLength(500)]
        public string mobilenumber { get; set; }
        [StringLength(500)]
        public string emailid { get; set; }
        [StringLength(50)]
        public string fulltime { get; set; }
        [StringLength(50)]
        public string parttime { get; set; }
        public string createdate { get; set; }
        [Key]
        public long referencenumber { get; set; }
        [StringLength(50)]
        public string ip { get; set; }
        [StringLength(500)]
        public string finalsubmit { get; set; }
        [StringLength(50)]
        public string finalsubmitdate { get; set; }
    }
}