// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class qpr_new
    {
        [StringLength(50)]
        public string userid { get; set; }
        [StringLength(100)]
        public string orgname { get; set; }
        [StringLength(50)]
        public string orgcode { get; set; }
        public byte? qtrreport { get; set; }
        public short? qtryear { get; set; }
        [StringLength(1)]
        public string contactnumberoffice { get; set; }
        [StringLength(1)]
        public string mobilenumber { get; set; }
        [StringLength(50)]
        public string emailid { get; set; }
        public bool? fulltime { get; set; }
        public bool? parttime { get; set; }
        [StringLength(1)]
        public string createdate { get; set; }
        public short? referencenumber { get; set; }
        [StringLength(1)]
        public string ip { get; set; }
        public bool? finalsubmit { get; set; }
        [StringLength(1)]
        public string finalsubmitdate { get; set; }
    }
}