// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class registration
    {
        [Key]
        public long usercode { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string organisation { get; set; }
        public string logintype { get; set; }
        public string loginroll { get; set; }
        public string desiganation { get; set; }
        public string createdate { get; set; }
        public string tenure { get; set; }
        public string bofficercode { get; set; }
        public string cvocode { get; set; }
        public string mobilenumber { get; set; }
        public string islocked { get; set; }
        public string lastmodified { get; set; }
        public string passwordone { get; set; }
        public string passwordtwo { get; set; }
        public string postid { get; set; }
        public string firstlogin { get; set; }
        public string status { get; set; }
        public string cvocontactnumberoffice { get; set; }
        public string fulltime { get; set; }
        public string parttime { get; set; }
    }
}