// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class sstage
    {
        public int? section { get; set; }
        [StringLength(500)]
        public string file_no { get; set; }
        public int? sno { get; set; }
        public string ssadvcode { get; set; }
        public string sscompdt { get; set; }
        public string sssendt { get; set; }
        public string ssrecon_dept_code { get; set; }
        public string ssrecon_dept_dt { get; set; }
        public string ssrecon_comm_code { get; set; }
        public string ssrecon_comm_comp_dt { get; set; }
        public string ssrecon_comm_sen_dt { get; set; }
        public string dt_sent_cvo { get; set; }
        public string dt_recd_cvo { get; set; }
        public string last_updated { get; set; }
    }
}