// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class statusofpendencyqrs
    {
        public int? pendency_status_id { get; set; }
        public long? pendency_status_fi_previousqtr { get; set; }
        public long? pendency_status_fi_addduringqtr { get; set; }
        public long? pendency_status_fi_total { get; set; }
        public long? pendency_status_fi_reply_commission { get; set; }
        public long? pendency_status_fi_reply_pending { get; set; }
        public long? pendency_status_fi_greaterthree { get; set; }
        public long? pendency_status_fi_threetosix { get; set; }
        public long? pendency_status_fi_sixtotwelve { get; set; }
        public long? pendency_status_fi_lessone { get; set; }
        public string pendency_status_fi_upload { get; set; }
        public long? pendency_status_ca_previousqtr { get; set; }
        public long? pendency_status_ca_addduringqtr { get; set; }
        public long? pendency_status_ca_total { get; set; }
        public long? pendency_status_ca_comments_commission { get; set; }
        public long? pendency_status_ca_comments_pending { get; set; }
        public long? pendency_status_ca_greaterone { get; set; }
        public long? pendency_status_ca_onetotwo { get; set; }
        public long? pendency_status_ca_twotothree { get; set; }
        public long? pendency_status_ca_lessthree { get; set; }
        public string pendency_status_ca_upload { get; set; }
        [StringLength(100)]
        public string create_date { get; set; }
        [StringLength(100)]
        public string user_id { get; set; }
        [StringLength(100)]
        public string update_date { get; set; }
        [StringLength(100)]
        public string last_user_id { get; set; }
        [StringLength(100)]
        public string qpr_id { get; set; }
        [StringLength(100)]
        public string ip { get; set; }
    }
}