// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class transfer
    {
        [StringLength(2000)]
        public string fromaccount { get; set; }
        [StringLength(2000)]
        public string toaccount { get; set; }
        [StringLength(2000)]
        public string timestamp { get; set; }
        [StringLength(100)]
        public string ipaddress { get; set; }
        public string complaint { get; set; }
        [StringLength(2000)]
        public string transfer_id { get; set; }
    }
}