// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class usercomplaintdetail
    {
        [Key]
        public int complaintnumber { get; set; }
        [StringLength(255)]
        public string com_date { get; set; }
        [StringLength(255)]
        public string sname { get; set; }
        [StringLength(255)]
        public string willingdepose { get; set; }
        [StringLength(255)]
        public string email { get; set; }
        [StringLength(255)]
        public string mobileno { get; set; }
        [StringLength(255)]
        public string complaintagainstname { get; set; }
        [StringLength(255)]
        public string post { get; set; }
    }
}