// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class userregister_detail
    {
        [Required]
        [StringLength(50)]
        public string username { get; set; }
        [Required]
        [StringLength(50)]
        public string password { get; set; }
        [Required]
        [StringLength(50)]
        public string confpassword { get; set; }
        [Required]
        [StringLength(50)]
        public string securityquestion { get; set; }
        [Required]
        [StringLength(50)]
        public string answer { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(1)]
        public string dateofbirth { get; set; }
        public long mobileno { get; set; }
        [Required]
        [StringLength(50)]
        public string emailid { get; set; }
        [StringLength(1)]
        public string nationality { get; set; }
        [Required]
        [StringLength(50)]
        public string address1 { get; set; }
        [StringLength(1)]
        public string address2 { get; set; }
        [StringLength(1)]
        public string district { get; set; }
        [StringLength(1)]
        public string taluka { get; set; }
        [StringLength(1)]
        public string village { get; set; }
        public int? pincode { get; set; }
        [StringLength(50)]
        public string satutation { get; set; }
        public byte? age { get; set; }
        [StringLength(50)]
        public string idcard { get; set; }
        [StringLength(50)]
        public string address { get; set; }
        [StringLength(50)]
        public string state { get; set; }
        [StringLength(50)]
        public string city { get; set; }
    }
}