// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class vig_case
    {
        public string section { get; set; }
        public string file_no { get; set; }
        public string file_open_dt { get; set; }
        public string inc_occ_dt { get; set; }
        public string inc_rep_dt { get; set; }
        public string source { get; set; }
        public string cbi_fir_no { get; set; }
        public string cbi_rec { get; set; }
        public string cbi_rec_dt { get; set; }
        public string comp_typ { get; set; }
        public string sent_inv { get; set; }
        public string inv_dt { get; set; }
        public string inv_agen { get; set; }
        public string imp_flag { get; set; }
        public string dt_sent_cvo { get; set; }
        public string retn_dt { get; set; }
        public string boffcode { get; set; }
        public string last_updated { get; set; }
        public string inv_typ { get; set; }
        public string chg_invtyp { get; set; }
        public string fast_track { get; set; }
        public string complaint_no { get; set; }
    }
}