// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace QPR_Application.Models.Entities
{
    public partial class viginvestigationqrs
    {
        [Key]
        public int viginvestigations_id { get; set; }
        public int viginvescvcopeningbalance { get; set; }
        public int viginvescvctakeninvesqtr { get; set; }
        public int viginvescvctotal { get; set; }
        public int viginvescvcreportsrecivqtr { get; set; }
        public int viginvescvcbalancepending { get; set; }
        public int viginvescvcgreaterthree { get; set; }
        public int viginvescvcthreetosix { get; set; }
        public int viginvescvcsixtotwelve { get; set; }
        public int viginvescvclesstwelve { get; set; }
        public int viginvescvoopeningbalance { get; set; }
        public int viginvescvotakeninvesqtr { get; set; }
        public int viginvescvototal { get; set; }
        public int viginvescvoreportsrecivqtr { get; set; }
        public int viginvescvobalancepending { get; set; }
        public int viginvescvogreaterthree { get; set; }
        public int viginvescvothreetosix { get; set; }
        public int viginvescvosixtotwelve { get; set; }
        public int viginvescvolesstwelve { get; set; }
        public int viginvestotalopeningbalance { get; set; }
        public int viginvestotaltakeninvesqtr { get; set; }
        public int viginvestotal { get; set; }
        public int viginvestotalreportsrecivqtr { get; set; }
        public int viginvestotalbalancepending { get; set; }
        public int viginvestotalgreaterthree { get; set; }
        public int viginvestotalthreetosix { get; set; }
        public int viginvestotalsixtotwelve { get; set; }
        public int viginvestotallesstwelve { get; set; }
        public int viginvespendingopeningpending { get; set; }
        public int viginvespendinginvestqtr { get; set; }
        public int viginvespendingtotal { get; set; }
        public int viginvespendingreportio { get; set; }
        public int viginvespendingbalancepending { get; set; }
        public int viginvespendinggreaterthree { get; set; }
        public int viginvespendingthreetosix { get; set; }
        public int viginvespendingsixtotwelve { get; set; }
        public int viginvestacbireceiveqtr { get; set; }
        public int viginvestacbitotal { get; set; }
        public int viginvestacbidisposedqtr { get; set; }
        public int viginvestacbibalancepending { get; set; }
        public int viginvestacbigreaterthree { get; set; }
        public int viginvestacbithreetosix { get; set; }
        public int viginvestacbisixtotwelve { get; set; }
        public int viginvestacbilesstwelve { get; set; }
        public int viginvestacvoreportqtr { get; set; }
        public int viginvestacvoreceiveqtr { get; set; }
        public int viginvestacvototal { get; set; }
        public int viginvestacvodisposedqtr { get; set; }
        public int viginvestacvobalancepending { get; set; }
        public int viginvestacvogreaterthree { get; set; }
        public int viginvestacvothreetosix { get; set; }
        public int viginvestacvosixtotwelve { get; set; }
        public int viginvestacvolesstwelve { get; set; }
        public int viginvestatotalreportqtr { get; set; }
        public int viginvestatotalreceiveqtr { get; set; }
        public int viginvestatotal { get; set; }
        public int viginvestatotaldisposedqtr { get; set; }
        public int viginvestatotalbalancepending { get; set; }
        public int viginvestatotalgreaterthree { get; set; }
        public int viginvestatotalthreetosix { get; set; }
        public int viginvestatotalsixtotwelve { get; set; }
        public int viginvestatotallesstwelve { get; set; }
        public int viginvestardamajorpenalty { get; set; }
        public int viginvestardaminorpenalty { get; set; }
        public int viginvestadecisionadminaction { get; set; }
        public int viginvestadecisionclosurecase { get; set; }
        public int viginvestbcbireportbfqtr { get; set; }
        public int viginvestbcbireceiveqtr { get; set; }
        public int viginvestbcbitotal { get; set; }
        public int viginvestbcbisentdaaction { get; set; }
        public int viginvestbcbidisposedqtr { get; set; }
        public int viginvestbcbibalancepending { get; set; }
        public int viginvestbcbigreaterthree { get; set; }
        public int viginvestbcbithreetosix { get; set; }
        public int viginvestbcbisixtotwelve { get; set; }
        public int viginvestbcbilesstwelve { get; set; }
        public int viginvestbcvoreportbfqtr { get; set; }
        public int viginvestbcvoreceiveqtr { get; set; }
        public int viginvestbcvototal { get; set; }
        public int viginvestbcvosentdaaction { get; set; }
        public int viginvestbcvodisposedqtr { get; set; }
        public int viginvestbcvobalancepending { get; set; }
        public int viginvestbcvogreaterthree { get; set; }
        public int viginvestbcvothreetosix { get; set; }
        public int viginvestbcvosixtotwelve { get; set; }
        public int viginvestbcvolesstwelve { get; set; }
        public int viginvestbtotalreportbfqtr { get; set; }
        public int viginvestbtotalreceiveqtr { get; set; }
        public int viginvestbtotal { get; set; }
        public int viginvestbtotalsentdaaction { get; set; }
        public int viginvestbtotaldisposedqtr { get; set; }
        public int viginvestbtotalbalancepending { get; set; }
        public int viginvestbtotalgreaterthree { get; set; }
        public int viginvestbtotalthreetosix { get; set; }
        public int viginvestbtotalsixtotwelve { get; set; }
        public int viginvestbtotallesstwelve { get; set; }
        public int viginvestbrdamajorpenalty { get; set; }
        public int viginvestbrdaminorpenalty { get; set; }
        public int viginvestbdecisionadminaction { get; set; }
        public int viginvestbdecisionclosurecase { get; set; }
        public int viginvestreportbycvoqtr { get; set; }
        public int viginvestmajorpp { get; set; }
        public int viginvestminorpp { get; set; }
        public int viginvestotheradmnaction { get; set; }
        public int viginvestclosure { get; set; }
        public int viginvestreskgroupcmajorpp { get; set; }
        public int viginvestreskgroupcminorpp { get; set; }
        public int viginvestreskgroupcotheraction { get; set; }
        public int viginvestreskgroupcclosure { get; set; }
        public int viginvestreskgroupctotal { get; set; }
        public int viginvestreskgroupbmajorpp { get; set; }
        public int viginvestreskgroupbminorpp { get; set; }
        public int viginvestreskgroupbotheraction { get; set; }
        public int viginvestreskgroupbclosure { get; set; }
        public int viginvestreskgroupbtotal { get; set; }
        public int viginvestreskgroupamajorpp { get; set; }
        public int viginvestreskgroupaminorpp { get; set; }
        public int viginvestreskgroupaotheraction { get; set; }
        public int viginvestreskgroupaclosure { get; set; }
        public int viginvestreskgroupatotal { get; set; }
        public int viginvestreskgroupjsmajorpp { get; set; }
        public int viginvestreskgroupjsminorpp { get; set; }
        public int viginvestreskgroupjsotheraction { get; set; }
        public int viginvestreskgroupjsclosure { get; set; }
        public int viginvestreskgroupjstotal { get; set; }
        public int viginvestresktotalmajorpp { get; set; }
        public int viginvestresktotalminorpp { get; set; }
        public int viginvestresktotalotheraction { get; set; }
        public int viginvestresktotalclosure { get; set; }
        public int viginvestresktotal { get; set; }
        public string create_date { get; set; }
        public string user_id { get; set; }
        public string update_date { get; set; }
        public string last_user_id { get; set; }
        public long qpr_id { get; set; }
        public string ip { get; set; }
        public string viginvespendinglesstwelve { get; set; }
        public int viginvestacbireportqtr { get; set; }
        public viginvestigationqrs()
        {
            viginvestigations_id = 0;
            viginvescvcopeningbalance = 0;
            viginvescvctakeninvesqtr = 0;
            viginvescvctotal = 0;
            viginvescvcreportsrecivqtr = 0;
            viginvescvcbalancepending = 0;
            viginvescvcgreaterthree = 0;
            viginvescvcthreetosix = 0;
            viginvescvcsixtotwelve = 0;
            viginvescvclesstwelve = 0;
            viginvescvoopeningbalance = 0;
            viginvescvotakeninvesqtr = 0;
            viginvescvototal = 0;
            viginvescvoreportsrecivqtr = 0;
            viginvescvobalancepending = 0;
            viginvescvogreaterthree = 0;
            viginvescvothreetosix = 0;
            viginvescvosixtotwelve = 0;
            viginvescvolesstwelve = 0;
            viginvestotalopeningbalance = 0;
            viginvestotaltakeninvesqtr = 0;
            viginvestotal = 0;
            viginvestotalreportsrecivqtr = 0;
            viginvestotalbalancepending = 0;
            viginvestotalgreaterthree = 0;
            viginvestotalthreetosix = 0;
            viginvestotalsixtotwelve = 0;
            viginvestotallesstwelve = 0;
            viginvespendingopeningpending = 0;
            viginvespendinginvestqtr = 0;
            viginvespendingtotal = 0;
            viginvespendingreportio = 0;
            viginvespendingbalancepending = 0;
            viginvespendinggreaterthree = 0;
            viginvespendingthreetosix = 0;
            viginvespendingsixtotwelve = 0;
            viginvestacbireceiveqtr = 0;
            viginvestacbitotal = 0;
            viginvestacbidisposedqtr = 0;
            viginvestacbibalancepending = 0;
            viginvestacbigreaterthree = 0;
            viginvestacbithreetosix = 0;
            viginvestacbisixtotwelve = 0;
            viginvestacbilesstwelve = 0;
            viginvestacvoreportqtr = 0;
            viginvestacvoreceiveqtr = 0;
            viginvestacvototal = 0;
            viginvestacvodisposedqtr = 0;
            viginvestacvobalancepending = 0;
            viginvestacvogreaterthree = 0;
            viginvestacvothreetosix = 0;
            viginvestacvosixtotwelve = 0;
            viginvestacvolesstwelve = 0;
            viginvestatotalreportqtr = 0;
            viginvestatotalreceiveqtr = 0;
            viginvestatotal = 0;
            viginvestatotaldisposedqtr = 0;
            viginvestatotalbalancepending = 0;
            viginvestatotalgreaterthree = 0;
            viginvestatotalthreetosix = 0;
            viginvestatotalsixtotwelve = 0;
            viginvestatotallesstwelve = 0;
            viginvestardamajorpenalty = 0;
            viginvestardaminorpenalty = 0;
            viginvestadecisionadminaction = 0;
            viginvestadecisionclosurecase = 0;
            viginvestbcbireportbfqtr = 0;
            viginvestbcbireceiveqtr = 0;
            viginvestbcbitotal = 0;
            viginvestbcbisentdaaction = 0;
            viginvestbcbidisposedqtr = 0;
            viginvestbcbibalancepending = 0;
            viginvestbcbigreaterthree = 0;
            viginvestbcbithreetosix = 0;
            viginvestbcbisixtotwelve = 0;
            viginvestbcbilesstwelve = 0;
            viginvestbcvoreportbfqtr = 0;
            viginvestbcvoreceiveqtr = 0;
            viginvestbcvototal = 0;
            viginvestbcvosentdaaction = 0;
            viginvestbcvodisposedqtr = 0;
            viginvestbcvobalancepending = 0;
            viginvestbcvogreaterthree = 0;
            viginvestbcvothreetosix = 0;
            viginvestbcvosixtotwelve = 0;
            viginvestbcvolesstwelve = 0;
            viginvestbtotalreportbfqtr = 0;
            viginvestbtotalreceiveqtr = 0;
            viginvestbtotal = 0;
            viginvestbtotalsentdaaction = 0;
            viginvestbtotaldisposedqtr = 0;
            viginvestbtotalbalancepending = 0;
            viginvestbtotalgreaterthree = 0;
            viginvestbtotalthreetosix = 0;
            viginvestbtotalsixtotwelve = 0;
            viginvestbtotallesstwelve = 0;
            viginvestbrdamajorpenalty = 0;
            viginvestbrdaminorpenalty = 0;
            viginvestbdecisionadminaction = 0;
            viginvestbdecisionclosurecase = 0;
            viginvestreportbycvoqtr = 0;
            viginvestmajorpp = 0;
            viginvestminorpp = 0;
            viginvestotheradmnaction = 0;
            viginvestclosure = 0;
            viginvestreskgroupcmajorpp = 0;
            viginvestreskgroupcminorpp = 0;
            viginvestreskgroupcotheraction = 0;
            viginvestreskgroupcclosure = 0;
            viginvestreskgroupctotal = 0;
            viginvestreskgroupbmajorpp = 0;
            viginvestreskgroupbminorpp = 0;
            viginvestreskgroupbotheraction = 0;
            viginvestreskgroupbclosure = 0;
            viginvestreskgroupbtotal = 0;
            viginvestreskgroupamajorpp = 0;
            viginvestreskgroupaminorpp = 0;
            viginvestreskgroupaotheraction = 0;
            viginvestreskgroupaclosure = 0;
            viginvestreskgroupatotal = 0;
            viginvestreskgroupjsmajorpp = 0;
            viginvestreskgroupjsminorpp = 0;
            viginvestreskgroupjsotheraction = 0;
            viginvestreskgroupjsclosure = 0;
            viginvestreskgroupjstotal = 0;
            viginvestresktotalmajorpp = 0;
            viginvestresktotalminorpp = 0;
            viginvestresktotalotheraction = 0;
            viginvestresktotalclosure = 0;
            viginvestresktotal = 0;
            create_date = string.Empty;
            user_id = string.Empty;
            update_date = string.Empty;
            last_user_id = string.Empty;
            qpr_id = 0;
            ip = string.Empty;
            viginvespendinglesstwelve = string.Empty;
            viginvestacbireportqtr = 0;
        }
    }
}