// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class vigilanceactivitiescvcqrs
    {
        [Required]
        public string vigilance_activites_id { get; set; }
        public string vigilance_activites_upload_doc { get; set; }
        public string vigilance_activites_any_remark { get; set; }
        public string vigilance_activites_place { get; set; }
        [Required]
        public string vigilance_activites_date { get; set; }
        [Required]
        public string create_date { get; set; }
        [Required]
        public string user_id { get; set; }
        [Required]
        public string update_date { get; set; }
        [Required]
        public string last_user_id { get; set; }
        [Required]
        public string qpr_id { get; set; }
        [Required]
        public string ip { get; set; }
    }
}