// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    public partial class vigilanceactivitiescvcqrs
    {
        [Key]
        public int vigilance_activites_id { get; set; }
        public string? vigilance_activites_upload_doc { get; set; }
        public string? vigilance_activites_any_remark { get; set; }
        public string? vigilance_activites_place { get; set; }
        public DateOnly? vigilance_activites_date { get; set; }
        public DateOnly? create_date { get; set; }
        public string user_id { get; set; }
        public DateOnly? update_date { get; set; }
        public string? last_user_id { get; set; }
        public long qpr_id { get; set; }
        public string ip { get; set; }
    }
}