// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class viginvestigationqrs
    {
        public string viginvestigations_id { get; set; }
        public string viginvescvcopeningbalance { get; set; }
        public string viginvescvctakeninvesqtr { get; set; }
        public string viginvescvctotal { get; set; }
        public string viginvescvcreportsrecivqtr { get; set; }
        public string viginvescvcbalancepending { get; set; }
        public string viginvescvcgreaterthree { get; set; }
        public string viginvescvcthreetosix { get; set; }
        public string viginvescvcsixtotwelve { get; set; }
        public string viginvescvclesstwelve { get; set; }
        public string viginvescvoopeningbalance { get; set; }
        public string viginvescvotakeninvesqtr { get; set; }
        public string viginvescvototal { get; set; }
        public string viginvescvoreportsrecivqtr { get; set; }
        public string viginvescvobalancepending { get; set; }
        public string viginvescvogreaterthree { get; set; }
        public string viginvescvothreetosix { get; set; }
        public string viginvescvosixtotwelve { get; set; }
        public string viginvescvolesstwelve { get; set; }
        public string viginvestotalopeningbalance { get; set; }
        public string viginvestotaltakeninvesqtr { get; set; }
        public string viginvestotal { get; set; }
        public string viginvestotalreportsrecivqtr { get; set; }
        public string viginvestotalbalancepending { get; set; }
        public string viginvestotalgreaterthree { get; set; }
        public string viginvestotalthreetosix { get; set; }
        public string viginvestotalsixtotwelve { get; set; }
        public string viginvestotallesstwelve { get; set; }
        public string viginvespendingopeningpending { get; set; }
        public string viginvespendinginvestqtr { get; set; }
        public string viginvespendingtotal { get; set; }
        public string viginvespendingreportio { get; set; }
        public string viginvespendingbalancepending { get; set; }
        public string viginvespendinggreaterthree { get; set; }
        public string viginvespendingthreetosix { get; set; }
        public string viginvespendingsixtotwelve { get; set; }
        public string viginvestacbireceiveqtr { get; set; }
        public string viginvestacbitotal { get; set; }
        public string viginvestacbidisposedqtr { get; set; }
        public string viginvestacbibalancepending { get; set; }
        public string viginvestacbigreaterthree { get; set; }
        public string viginvestacbithreetosix { get; set; }
        public string viginvestacbisixtotwelve { get; set; }
        public string viginvestacbilesstwelve { get; set; }
        public string viginvestacvoreportqtr { get; set; }
        public string viginvestacvoreceiveqtr { get; set; }
        public string viginvestacvototal { get; set; }
        public string viginvestacvodisposedqtr { get; set; }
        public string viginvestacvobalancepending { get; set; }
        public string viginvestacvogreaterthree { get; set; }
        public string viginvestacvothreetosix { get; set; }
        public string viginvestacvosixtotwelve { get; set; }
        public string viginvestacvolesstwelve { get; set; }
        public string viginvestatotalreportqtr { get; set; }
        public string viginvestatotalreceiveqtr { get; set; }
        public string viginvestatotal { get; set; }
        public string viginvestatotaldisposedqtr { get; set; }
        public string viginvestatotalbalancepending { get; set; }
        public string viginvestatotalgreaterthree { get; set; }
        public string viginvestatotalthreetosix { get; set; }
        public string viginvestatotalsixtotwelve { get; set; }
        public string viginvestatotallesstwelve { get; set; }
        public string viginvestardamajorpenalty { get; set; }
        public string viginvestardaminorpenalty { get; set; }
        public string viginvestadecisionadminaction { get; set; }
        public string viginvestadecisionclosurecase { get; set; }
        public string viginvestbcbireportbfqtr { get; set; }
        public string viginvestbcbireceiveqtr { get; set; }
        public string viginvestbcbitotal { get; set; }
        public string viginvestbcbisentdaaction { get; set; }
        public string viginvestbcbidisposedqtr { get; set; }
        public string viginvestbcbibalancepending { get; set; }
        public string viginvestbcbigreaterthree { get; set; }
        public string viginvestbcbithreetosix { get; set; }
        public string viginvestbcbisixtotwelve { get; set; }
        public string viginvestbcbilesstwelve { get; set; }
        public string viginvestbcvoreportbfqtr { get; set; }
        public string viginvestbcvoreceiveqtr { get; set; }
        public string viginvestbcvototal { get; set; }
        public string viginvestbcvosentdaaction { get; set; }
        public string viginvestbcvodisposedqtr { get; set; }
        public string viginvestbcvobalancepending { get; set; }
        public string viginvestbcvogreaterthree { get; set; }
        public string viginvestbcvothreetosix { get; set; }
        public string viginvestbcvosixtotwelve { get; set; }
        public string viginvestbcvolesstwelve { get; set; }
        public string viginvestbtotalreportbfqtr { get; set; }
        public string viginvestbtotalreceiveqtr { get; set; }
        public string viginvestbtotal { get; set; }
        public string viginvestbtotalsentdaaction { get; set; }
        public string viginvestbtotaldisposedqtr { get; set; }
        public string viginvestbtotalbalancepending { get; set; }
        public string viginvestbtotalgreaterthree { get; set; }
        public string viginvestbtotalthreetosix { get; set; }
        public string viginvestbtotalsixtotwelve { get; set; }
        public string viginvestbtotallesstwelve { get; set; }
        public string viginvestbrdamajorpenalty { get; set; }
        public string viginvestbrdaminorpenalty { get; set; }
        public string viginvestbdecisionadminaction { get; set; }
        public string viginvestbdecisionclosurecase { get; set; }
        public string viginvestreportbycvoqtr { get; set; }
        public string viginvestmajorpp { get; set; }
        public string viginvestminorpp { get; set; }
        public string viginvestotheradmnaction { get; set; }
        public string viginvestclosure { get; set; }
        public string viginvestreskgroupcmajorpp { get; set; }
        public string viginvestreskgroupcminorpp { get; set; }
        public string viginvestreskgroupcotheraction { get; set; }
        public string viginvestreskgroupcclosure { get; set; }
        public string viginvestreskgroupctotal { get; set; }
        public string viginvestreskgroupbmajorpp { get; set; }
        public string viginvestreskgroupbminorpp { get; set; }
        public string viginvestreskgroupbotheraction { get; set; }
        public string viginvestreskgroupbclosure { get; set; }
        public string viginvestreskgroupbtotal { get; set; }
        public string viginvestreskgroupamajorpp { get; set; }
        public string viginvestreskgroupaminorpp { get; set; }
        public string viginvestreskgroupaotheraction { get; set; }
        public string viginvestreskgroupaclosure { get; set; }
        public string viginvestreskgroupatotal { get; set; }
        public string viginvestreskgroupjsmajorpp { get; set; }
        public string viginvestreskgroupjsminorpp { get; set; }
        public string viginvestreskgroupjsotheraction { get; set; }
        public string viginvestreskgroupjsclosure { get; set; }
        public string viginvestreskgroupjstotal { get; set; }
        public string viginvestresktotalmajorpp { get; set; }
        public string viginvestresktotalminorpp { get; set; }
        public string viginvestresktotalotheraction { get; set; }
        public string viginvestresktotalclosure { get; set; }
        public string viginvestresktotal { get; set; }
        public string create_date { get; set; }
        public string user_id { get; set; }
        public string update_date { get; set; }
        public string last_user_id { get; set; }
        public string qpr_id { get; set; }
        public string ip { get; set; }
        public string viginvespendinglesstwelve { get; set; }
        public string viginvestacbireportqtr { get; set; }
    }
}