// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class vijclearanceofficerdetail
    {
        public string id { get; set; }
        public string fileno { get; set; }
        public string nameofofficer { get; set; }
        public string service { get; set; }
        public string batch { get; set; }
        public string cadre { get; set; }
        public string empcode { get; set; }
        public string finaldecisiondd { get; set; }
        public string finaldecisiondate { get; set; }
        public string dateofbirth { get; set; }
        public string dateofretirement { get; set; }
    }
}