// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QPR_Application.Models.Entities
{
    [Keyless]
    public partial class workex
    {
        public string workex_id { get; set; }
        public string profile_id { get; set; }
        public string orgname { get; set; }
        public string experience { get; set; }
        public string orgcode { get; set; }
    }
}